### ISSUE TITLE
Add PlayerOffsets with the json and ..

### ISSUE THREAD

**Issue by THOBY555** [Luisinhi010/BEAT-engine#1]
### What feature do you want to get added on the **base** engine?

Add PlayerOffsets with the json and Stage X/Y + script like a script named the same as the character name on the character file have the stages name and X/Y Array 

### To test your sight, and reliability, please select the option of what should NOT be requested.

Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)

**Comment by Gui-iago** [comment]
![image](https://user-images.githubusercontent.com/45212377/151265006-f2553599-0af7-48d9-9d2d-5d8cb9351c1a.png)

also, no, you can just make multiple config files, this would take ages to get working properly and we probably don't wanna revert back to the old method of doing offsets
