### ISSUE TITLE
im trying to export but it says its damaged

### ISSUE THREAD

**Issue by Jsa010** [Luisinhi010/BEAT-engine#2]
### Describe your bug here.

HELP HELP AAAAAAA WITH THE PRE-RELEASE AND THE 0.0.1 HAPPEND TOO :(

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

i didn't edited anythink

**Comment by Luisinhi010** [comment]
you need to have the latest version of haxe, read the README.md for better explanation

**Comment by Gui-iago** [comment]
read the main page.

**Comment by Jsa010** [comment]
@Luisinhi010 BUT I ALREADY HAVE THE VERSION AND IT STILL SAYING THE ZIP IS DAMAGED
