### ISSUE TITLE
PLZ USE THIS PLZZZ

### ISSUE THREAD

**Issue by matt-sudo-jpg** [Luisinhi010/BEAT-engine#4]
ignore this shit

**Comment by ThatOneCalculator** [comment]
Why would you link an exe and the source code with Dropbox? Git repos exist for a reason, you could've forked this project and made a pull request, like a normal person.

**Comment by matt-sudo-jpg** [comment]
> 

o shit i didnt knew and reason why i didnt use git cause git said it was too much or some shit but imma delete it n make a fork

**Comment by ThatOneCalculator** [comment]
> ignore this shit

Then...close the issue?
